title: Kalu Goodness C.
description: My Data Portfolio
logo: assets/img/profile_pic_no_bg.png
# show_downloads: true
theme: jekyll-theme-minimal
author:
  name: Kalu Goodness
  email: drkalugoodness@gmail.com
